### ISSUE TITLE
could not find the config file

### ISSUE THREAD

**Issue by CuWO4** [MestreLion/hackmatch#1]
main: Could not find the game config folder: C:\Users\Tony\Documents\My Games\EXAPUNKS\*\config.cfg

however, i'm sure config.cfg can be found from the certain path, and i can't edit the program because it's a exe file.

what should i do, appreciation.

**Comment by MestreLion** [comment]
Can you paste the full error messages from running this as `hackmatch-bot --verbose`? And also, what is the actual full path to your game `config.cfg`?

Please enclose both in "triple backsticks", so it does not get re-formatted by github

**Comment by Aratietur** [comment]
Hi, had the same problem because my path is:
C:\Users\nikol\OneDrive\Dokumente\My Games\EXAPUNKS <-- and i can't change the"Onedrive\Dokumente"-part.
But i had rewritten your automated config path to a fixed one and it works this way.
just got me to the next problem, but i will post this in a new Issue

**Comment by MestreLion** [comment]
It seems getting the proper Documents folder in Python is far from trivial... I've read a dozen different posts each with very different solutions (and requirements, and robustness).

@Aratietur , care to check if this works for you?

```
# From https://stackoverflow.com/a/30924555/624066
import ctypes.wintypes
CSIDL_PERSONAL = 5       # My Documents
SHGFP_TYPE_CURRENT = 0   # Get current, not default value

buf= ctypes.create_unicode_buffer(ctypes.wintypes.MAX_PATH)
ctypes.windll.shell32.SHGetFolderPathW(None, CSIDL_PERSONAL, None, SHGFP_TYPE_CURRENT, buf)

print(buf.value)
```

Does this prints  `C:\Users\nikol\OneDrive\Dokumente`?

**Comment by Aratietur** [comment]
yes it works:

C:\Users\nikol>python
Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> # From https://stackoverflow.com/a/30924555/624066
>>> import ctypes.wintypes
>>> CSIDL_PERSONAL = 5       # My Documents
>>> SHGFP_TYPE_CURRENT = 0   # Get current, not default value
>>>
>>> buf= ctypes.create_unicode_buffer(ctypes.wintypes.MAX_PATH)
>>> ctypes.windll.shell32.SHGetFolderPathW(None, CSIDL_PERSONAL, None, SHGFP_TYPE_CURRENT, buf)
0
>>>
>>> print(buf.value)
C:\Users\nikol\OneDrive\Dokumente
>>> print(buf.value)

**Comment by MestreLion** [comment]
Awesome! I'll use this method to determine the game config path in Windows
